// lib/reducer.ts
// 🎯 This file contains our STATE MANAGEMENT logic using useReducer

// 🎯 LEARNING: Import types from our components
import { Node, Edge } from "@/components/generative-ai/ArchitectureCanvas";

// 🎯 STEP 1: Define the STATE SHAPE
// This is the BLUEPRINT of our data structure
export interface AppState {
  // User input
  prompt: string;

  // Architecture data (generated by AI)
  architecture: {
    nodes: Node[];
    edges: Edge[];
    explanations: string[];
  };

  // Loading state (is AI generating?)
  loadingState: {
    loading: boolean;
    aiThinking: string[];
  };

  // UI state (what user sees)
  ui: {
    displayedText: string[];
    activeTab: "overview" | "best" | "cost";
  };
}

// 🎯 STEP 2: Define INITIAL STATE
// This is what the app looks like when it first loads
export const initialState: AppState = {
  prompt: "I want to build a scalable food delivery app like Swiggy",
  
  architecture: {
    nodes: [],
    edges: [],
    explanations: [],
  },
  
  loadingState: {
    loading: false,
    aiThinking: [],
  },
  
  ui: {
    displayedText: [],
    activeTab: "overview",
  },
};

// 🎯 STEP 3: Define ACTION TYPES
// These are all the things that can happen in our app
export type AppAction =
  | { type: "SET_PROMPT"; payload: string }
  | { type: "SET_ACTIVE_TAB"; payload: "overview" | "best" | "cost" }
  | { type: "GENERATE_START" }
  | { 
      type: "GENERATE_SUCCESS"; 
      payload: { 
        nodes: Node[]; 
        edges: Edge[]; 
        explanations: string[] 
      } 
    }
  | { type: "ADD_AI_THINKING"; payload: string }
  | { type: "ADD_DISPLAYED_TEXT"; payload: string }
  | { type: "CLEAR_DESIGN" }
  | { type: "RESET_DISPLAYED_TEXT" };

// 🎯 STEP 4: The REDUCER FUNCTION
// This is the "cashier" that processes your "order" (action)
// It takes: (current state, action) → returns new state
export function appReducer(state: AppState, action: AppAction): AppState {
  switch (action.type) {
    // 📝 User types in input box
    case "SET_PROMPT":
      return {
        ...state,
        prompt: action.payload,
      };

    // 🔄 User switches tab (Overview/Best/Cost)
    case "SET_ACTIVE_TAB":
      return {
        ...state,
        ui: {
          ...state.ui,
          activeTab: action.payload,
        },
      };

    // 🚀 User clicks "Generate" button
    case "GENERATE_START":
      return {
        ...state,
        loadingState: {
          loading: true,
          aiThinking: [],
        },
        architecture: {
          nodes: [],
          edges: [],
          explanations: [],
        },
        ui: {
          ...state.ui,
          displayedText: [],
        },
      };

    // ✅ AI finishes generating architecture
    case "GENERATE_SUCCESS":
      return {
        ...state,
        loadingState: {
          loading: false,
          aiThinking: [],
        },
        architecture: {
          nodes: action.payload.nodes,
          edges: action.payload.edges,
          explanations: action.payload.explanations,
        },
      };

    // 💭 Add AI thinking step (e.g., "Analyzing patterns...")
    case "ADD_AI_THINKING":
      return {
        ...state,
        loadingState: {
          ...state.loadingState,
          aiThinking: [...state.loadingState.aiThinking, action.payload],
        },
      };

    // 📄 Add explanation text one by one (typing effect)
    case "ADD_DISPLAYED_TEXT":
      return {
        ...state,
        ui: {
          ...state.ui,
          displayedText: [...state.ui.displayedText, action.payload],
        },
      };

    // 🗑️ User clicks "Clear" button
    case "CLEAR_DESIGN":
      return {
        ...state,
        architecture: {
          nodes: [],
          edges: [],
          explanations: [],
        },
        ui: {
          ...state.ui,
          displayedText: [],
        },
        loadingState: {
          loading: false,
          aiThinking: [],
        },
      };

    // 🔄 Reset displayed text (used before generating new)
    case "RESET_DISPLAYED_TEXT":
      return {
        ...state,
        ui: {
          ...state.ui,
          displayedText: [],
        },
      };

    // ⚠️ Unknown action - return state unchanged
    default:
      return state;
  }
}
